"""CBSE assessment reference data for rubric generation.

Everything in this module is *reference data*, not LLM output. It encodes the
CBSE Assessment Framework (British Council / AlphaPlus, March 2021):

  - Assessment Objectives (AOs) and their official percentage weightings,
    which differ per subject and per class.
  - The levels-of-response band structure: level count, mark bands, the
    controlled quality ladder, and the mandatory Level 0 "Nothing to reward".

Level descriptors are built here rather than generated by the LLM so that every
item of the same (marks, level-count) shape carries byte-identical bands. That
is what makes marking comparable across chapters, which is the entire point of
a standardised mark scheme.
"""

from __future__ import annotations

from typing import Dict, List, Tuple

# ==========================================================
# ASSESSMENT OBJECTIVES
# Source: CBSE Assessment Framework pp.16 (English), 66 (Maths), 144 (Science)
# ==========================================================

# CBSE published this AO framework for Classes 6-10 only, and only for Science,
# Mathematics and English. Weightings for Classes 11-12 are DERIVED by carrying
# the published Class 9-10 values forward; they are flagged as such via
# ao_weightings_are_official() so nothing downstream presents them as CBSE fact.
_DERIVED_SENIOR = (11, 12)


def _extend_senior(weights: Dict[int, str]) -> Dict[int, str]:
    """Carry the published Class 10 weighting forward to Classes 11-12."""
    if 10 not in weights:
        return dict(weights)
    extended = dict(weights)
    for cls in _DERIVED_SENIOR:
        extended[cls] = weights[10]
    return extended


# subject family -> {ao_code: (description, {class: weighting})}
_SCIENCE_AO = {
    "AO1": ("Demonstrate knowledge and understanding of scientific ideas, techniques and procedures.",
            _extend_senior({6: "40", 7: "40", 8: "40", 9: "30", 10: "30"})),
    "AO2": ("Apply knowledge and understanding of scientific ideas, techniques and procedures to "
            "classroom and real-world situations.",
            _extend_senior({6: "40", 7: "40", 8: "40", 9: "30", 10: "30"})),
    "AO3": ("Analyse scientific information and ideas to present data and interpret patterns and relationships.",
            _extend_senior({6: "10", 7: "10", 8: "10", 9: "20", 10: "20"})),
    "AO4": ("Evaluate scientific information to make judgments, draw conclusions, and develop and improve "
            "experimental procedure.",
            _extend_senior({6: "10", 7: "10", 8: "10", 9: "20", 10: "20"})),
}

_MATHS_AO = {
    "AO1": ("Demonstrate knowledge and understanding of mathematical ideas, techniques and procedures.",
            _extend_senior({6: "50-65", 7: "50-65", 8: "50-65", 9: "40-55", 10: "40-55"})),
    "AO2": ("Apply knowledge and understanding of mathematical ideas, techniques and procedures to "
            "classroom and real-world situations.",
            _extend_senior({6: "35-50", 7: "35-50", 8: "35-50", 9: "45-60", 10: "45-60"})),
}

_ENGLISH_AO = {
    "AO1": ("Show understanding of explicit meanings.",
            _extend_senior({6: "40-48", 7: "40-48", 8: "40-48", 9: "23", 10: "23"})),
    "AO2": ("Show understanding of implicit meanings and perspectives.",
            _extend_senior({6: "40-48", 7: "40-48", 8: "40-48", 9: "23", 10: "23"})),
    "AO3": ("Comment on the effect of the writer's use of language and structure.",
            _extend_senior({9: "27", 10: "27"})),
    "AO4": ("Communicate a personal response to what is read, supported by textual reference.",
            _extend_senior({6: "12-16", 7: "12-16", 8: "12-16", 9: "27", 10: "27"})),
}

# Every subject outside the three published families falls back to this generic
# set, which mirrors the Science structure because the Science AOs are themselves
# subject-neutral (know / apply / analyse / evaluate).
_GENERIC_AO = {
    "AO1": ("Demonstrate knowledge and understanding of the ideas, terms and procedures of the subject.",
            _extend_senior({6: "40", 7: "40", 8: "40", 9: "30", 10: "30"})),
    "AO2": ("Apply knowledge and understanding to classroom and real-world situations.",
            _extend_senior({6: "40", 7: "40", 8: "40", 9: "30", 10: "30"})),
    "AO3": ("Analyse information and ideas to interpret patterns, relationships and meaning.",
            _extend_senior({6: "10", 7: "10", 8: "10", 9: "20", 10: "20"})),
    "AO4": ("Evaluate information to make judgments, draw conclusions and justify a position.",
            _extend_senior({6: "10", 7: "10", 8: "10", 9: "20", 10: "20"})),
}

# Subject families across the full K-12 CBSE offering. Matched on substrings of
# the subject name, most specific family first.
_SUBJECT_KEYWORDS: List[Tuple[Tuple[str, ...], Dict, str]] = [
    # Mathematics must be tested before Science: "Applied Mathematics" would
    # otherwise never be reached, and "Computer Science" must not match Science.
    (("mathematics", "maths", "math", "गणित", "applied mathematics"), _MATHS_AO, "Mathematics"),
    (("computer science", "informatics", "information technology", "artificial intelligence",
      "computer application", "coding", "data science"), _GENERIC_AO, "Computing"),
    # Humanities MUST be tested before Science: "Social Science" and "Political
    # Science" both contain the substring "science" and would otherwise be
    # misclassified into the Science AO family.
    (("social science", "history", "geography", "political science", "civics", "economics",
      "sociology", "psychology", "philosophy", "legal studies", "सामाजिक"), _GENERIC_AO, "Humanities"),
    (("science", "physics", "chemistry", "biology", "biotechnology", "विज्ञान",
      "environmental studies", "evs", "home science"), _SCIENCE_AO, "Science"),
    (("english", "hindi", "sanskrit", "urdu", "punjabi", "bengali", "tamil", "telugu",
      "marathi", "gujarati", "kannada", "malayalam", "odia", "assamese", "nepali",
      "french", "german", "spanish", "japanese", "arabic", "persian", "language",
      "हिंदी", "संस्कृत"), _ENGLISH_AO, "Language"),
    (("accountancy", "business studies", "entrepreneurship", "commerce"), _GENERIC_AO, "Commerce"),
    (("painting", "music", "dance", "fine art", "sculpture", "graphics", "fashion",
      "physical education", "yoga", "vocational", "skill"), _GENERIC_AO, "Arts & Skills"),
]


def _resolve_ao_set(subject_name: str) -> Tuple[Dict, str]:
    subject = (subject_name or "").strip().lower()
    for keywords, ao_set, family in _SUBJECT_KEYWORDS:
        if any(k in subject for k in keywords):
            return ao_set, family
    return _GENERIC_AO, "General"


def subject_family(subject_name: str) -> str:
    """Which AO family this subject resolves to. Useful for reporting."""
    return _resolve_ao_set(subject_name)[1]


def _parse_class(class_level: str) -> int:
    """Pull an integer class out of values like '10', 'Class 10', 'X'."""
    text = str(class_level or "").strip().lower()
    digits = "".join(ch for ch in text if ch.isdigit())
    if digits:
        try:
            cls = int(digits)
            if 1 <= cls <= 12:
                return cls
        except ValueError:
            pass
    # Roman numerals still appear in CBSE documents ("Class X", "Class XII").
    romans = {
        "xii": 12, "xi": 11, "ix": 9, "viii": 8, "vii": 7, "vi": 6,
        "iv": 4, "v": 5, "iii": 3, "ii": 2, "i": 1, "x": 10,
    }
    for token in sorted(romans, key=len, reverse=True):
        if f"class {token}" in text or text == token:
            return romans[token]
    return 10


# ==========================================================
# NEP STAGES
# Assessment works differently at different stages. Classes 1-5 are assessed
# with qualitative descriptors under the Holistic Progress Card, not with mark
# bands: awarding "9-10 marks" to a Class 2 child is not how CBSE/NCERT assess
# the Foundational and Preparatory stages.
# ==========================================================

STAGE_FOUNDATIONAL = "Foundational"    # Classes 1-2
STAGE_PREPARATORY = "Preparatory"      # Classes 3-5
STAGE_MIDDLE = "Middle"                # Classes 6-8
STAGE_SECONDARY = "Secondary"          # Classes 9-10
STAGE_SENIOR = "Senior Secondary"      # Classes 11-12


def nep_stage(class_level: str) -> str:
    cls = _parse_class(class_level)
    if cls <= 2:
        return STAGE_FOUNDATIONAL
    if cls <= 5:
        return STAGE_PREPARATORY
    if cls <= 8:
        return STAGE_MIDDLE
    if cls <= 10:
        return STAGE_SECONDARY
    return STAGE_SENIOR


def uses_mark_bands(class_level: str) -> bool:
    """Classes 1-5 are descriptor-based; Classes 6-12 use numeric mark bands."""
    return nep_stage(class_level) not in (STAGE_FOUNDATIONAL, STAGE_PREPARATORY)


def ao_weightings_are_official(subject_name: str, class_level: str) -> bool:
    """True only where CBSE actually published the weighting: Science,
    Mathematics and English, Classes 6-10."""
    cls = _parse_class(class_level)
    if not 6 <= cls <= 10:
        return False
    return subject_family(subject_name) in ("Science", "Mathematics", "Language") and \
        _resolve_ao_set(subject_name)[0] is not _GENERIC_AO


# Official CBSE question-paper composition for Classes 9-12 (2025-26 onwards).
_ITEM_MIX_SECONDARY_PLUS = (
    "50% competency-based questions (case-based, source-based, real-world application), "
    "20% multiple choice questions, "
    "30% constructed response (short and long answer)."
)


def item_mix_guidance(class_level: str) -> str:
    stage = nep_stage(class_level)
    if stage in (STAGE_SECONDARY, STAGE_SENIOR):
        return _ITEM_MIX_SECONDARY_PLUS
    if stage == STAGE_MIDDLE:
        return ("Favour understanding and application over recall. Include at least one "
                "case-based or real-world application item.")
    return ("Use short, concrete, activity-based tasks suited to young learners. "
            "Observation and oral evidence matter more than written answers.")


def valid_ao_codes(subject_name: str, class_level: str) -> List[str]:
    """AO codes valid for this subject and class (Maths has only AO1/AO2;
    English gains AO3 only from Class 9)."""
    cls = _parse_class(class_level)
    ao_set, _family = _resolve_ao_set(subject_name)
    codes = [code for code, (_desc, weights) in sorted(ao_set.items()) if cls in weights]
    if codes:
        return codes
    # Classes 1-5 sit outside the published tables. Fall back to the generic set
    # so young-learner rubrics still carry a cognitive label.
    return [code for code, (_desc, weights) in sorted(_GENERIC_AO.items()) if 6 in weights]


def build_ao_block(subject_name: str, class_level: str) -> str:
    """Render the AO table for injection into the Agent 4 prompt."""
    cls = _parse_class(class_level)
    ao_set, family = _resolve_ao_set(subject_name)
    official = ao_weightings_are_official(subject_name, class_level)

    lines = []
    for code, (desc, weights) in sorted(ao_set.items()):
        if cls not in weights:
            continue
        lines.append(f"- {code} ({weights[cls]}% of marks): {desc}")

    if not lines:
        # Classes 1-5: describe the objectives without percentage targets.
        for code in valid_ao_codes(subject_name, class_level):
            desc = _GENERIC_AO[code][0]
            lines.append(f"- {code}: {desc}")
        header = (f"Assessment objectives for the {nep_stage(class_level)} stage "
                  f"({family}). No fixed percentage weightings apply at this stage.")
        return header + "\n" + "\n".join(lines)

    if official:
        header = f"Official CBSE assessment objectives and weightings ({family}, Class {cls}):"
    else:
        header = (f"Assessment objectives for {family}, Class {cls}. NOTE: CBSE published "
                  f"weightings only for Science, Mathematics and English in Classes 6-10. "
                  f"The percentages below are derived as a reasonable target, not official CBSE figures:")
    return header + "\n" + "\n".join(lines)


# ==========================================================
# RUBRIC TYPE SELECTION
# Which mark-scheme shape CBSE uses for which item type.
# ==========================================================

# Minimum marks each item type can carry.
#
# Extended-response types are marked with levels of response, and a level table
# needs enough marks to build distinct bands: a 2-mark "Case Study" cannot be
# banded, which would leave the teacher with a question and no way to mark it.
# Enforced in code rather than left to the model, so it holds for every subject
# and every class.
MIN_MARKS_BY_ASSESSMENT_TYPE: Dict[str, int] = {
    "MCQ": 1,
    "Assertion Reason": 1,
    "Short Answer": 2,
    "Numerical": 2,
    "Long Answer": 4,
    "Case Study": 4,
    "HOTS": 4,
    "Competency Based Question": 4,
    "Practical": 5,
    "Viva": 5,
    "Project": 10,
}


def minimum_marks(assessment_type: str) -> int:
    return MIN_MARKS_BY_ASSESSMENT_TYPE.get(assessment_type, 1)


def min_marks_block() -> str:
    """Render the minimum-marks table for the Agent 4 prompt."""
    return "\n".join(
        f"  {a_type}: at least {m} mark{'s' if m > 1 else ''}"
        for a_type, m in MIN_MARKS_BY_ASSESSMENT_TYPE.items()
    )


RUBRIC_TYPE_BY_ASSESSMENT_TYPE: Dict[str, str] = {
    "MCQ": "answer_key",
    "Assertion Reason": "answer_key",
    "Short Answer": "point_based",
    "Numerical": "point_based",
    "Long Answer": "levels_of_response",
    "Case Study": "levels_of_response",
    "HOTS": "levels_of_response",
    "Competency Based Question": "levels_of_response",
    "Project": "analytical",
    "Practical": "analytical",
    "Viva": "analytical",
}


# ==========================================================
# LEVELS OF RESPONSE - BAND CONSTRUCTION
# Source: CBSE Assessment Framework pp.60, 63
# ==========================================================

# Controlled quality ladder. Each entry is
#   (quality_band, teacher-facing label, performance bullet, evidence bullet)
# The performance bullet takes the item's skill_phrase so the band reads as
# concept-specific prose while the progression vocabulary stays fixed.
_LADDER: List[Tuple[str, str, str, str]] = [
    ("Perceptive", "Excellent",
     "A perceptive and sustained analysis of {skill_phrase}",
     "Well-selected references from the material used as an integral part of the response"),
    ("Clear", "Good",
     "A clear, well-developed explanation of {skill_phrase}",
     "A wide range of relevant references used to support the response"),
    ("Generally Clear", "Fair",
     "A generally clear explanation of {skill_phrase}",
     "Relevant references used to support the explanation"),
    ("Straightforward", "Needs Improvement",
     "Some straightforward comment on {skill_phrase}",
     "Some detail used, beginning to support the comments"),
    ("Limited", "Beginning",
     "Limited awareness of {skill_phrase}",
     "Limited use of supporting detail"),
]


def level_count_for_marks(marks: int) -> int:
    """CBSE bands must be awardable. A 3-mark item cannot carry five levels."""
    if marks <= 2:
        return 0          # point-based territory, no levels
    if marks <= 4:
        return 3
    if marks <= 6:
        return 4
    return 5


def _mark_bands(marks: int, levels: int) -> List[Tuple[int, int]]:
    """Split 1..marks into `levels` contiguous, non-overlapping bands.

    Returned lowest-band-first. The top band always ends exactly at `marks`,
    and every mark from 1 to `marks` falls in exactly one band.
    """
    base, remainder = divmod(marks, levels)
    sizes = [base + (1 if i < remainder else 0) for i in range(levels)]
    bands: List[Tuple[int, int]] = []
    low = 1
    for size in sizes:
        bands.append((low, low + size - 1))
        low += size
    return bands


# Holistic Progress Card style scale for Classes 1-5. Descriptor-based, with no
# marks: NEP and the HPC assess the Foundational and Preparatory stages
# qualitatively rather than numerically.
_HPC_LADDER: List[Tuple[str, str, str]] = [
    ("Proficient", "Proficient", "Consistently and independently demonstrates {skill_phrase}"),
    ("Progressing", "Progressing", "Demonstrates {skill_phrase} with occasional support"),
    ("Beginner", "Beginner", "Beginning to demonstrate {skill_phrase}; needs regular support"),
]


def build_hpc_descriptors(skill_phrase: str) -> List[dict]:
    """Qualitative descriptor scale for Classes 1-5. Carries no marks."""
    return [
        {
            "level": len(_HPC_LADDER) - offset,
            "quality_band": quality,
            "display_label": label,
            "descriptors": [template.format(skill_phrase=skill_phrase)],
            "mark_low": 0,
            "mark_high": 0,
        }
        for offset, (quality, label, template) in enumerate(_HPC_LADDER)
    ]


def build_level_descriptors(marks: int, skill_phrase: str, class_level: str = "") -> List[dict]:
    """Build the CBSE levels-of-response table for an item.

    Descends from the highest level to Level 0 ("Nothing to reward", 0 marks),
    exactly as the framework exemplars on pp.60 and 63 do. For Classes 1-5 the
    numeric bands are replaced by the qualitative HPC scale.
    """
    if class_level and not uses_mark_bands(class_level):
        return build_hpc_descriptors(skill_phrase)

    levels = level_count_for_marks(marks)
    if levels == 0:
        return []

    # Take the top `levels` rungs of the ladder so that short items still start
    # at "Perceptive" and degrade to "Limited".
    rungs = _LADDER[:levels]
    bands = _mark_bands(marks, levels)  # lowest first

    descriptors: List[dict] = []
    # rungs[0] is the best band and pairs with the highest mark band.
    for offset, (quality, label, performance, evidence) in enumerate(rungs):
        low, high = bands[levels - 1 - offset]
        descriptors.append({
            "level": levels - offset,
            "quality_band": quality,
            "display_label": label,
            "descriptors": [
                performance.format(skill_phrase=skill_phrase),
                evidence,
            ],
            "mark_low": low,
            "mark_high": high,
        })

    descriptors.append({
        "level": 0,
        "quality_band": "Nothing to Reward",
        "display_label": "No Credit",
        "descriptors": ["Nothing to reward"],
        "mark_low": 0,
        "mark_high": 0,
    })
    return descriptors


# ==========================================================
# ANALYTICAL RUBRICS - CRITERION DESCRIPTORS
# For Project / Practical / Viva, mirroring CBSE internal assessment.
# ==========================================================

CRITERION_FOCUS: Dict[str, str] = {
    "Conceptual Understanding": "grasp of the underlying principles of the concept",
    "Scientific Method / Process": "use of appropriate method, sequence and procedure",
    "Data Handling & Accuracy": "recording, measurement and accuracy of data",
    "Analysis & Interpretation": "interpretation of results, patterns and relationships",
    "Application & Relevance": "connection of the concept to real-world contexts",
    "Presentation & Communication": "clarity, organisation and use of subject vocabulary",
    "Originality & Creativity": "independent thinking and originality of approach",
    "Record / Documentation": "completeness and neatness of the written record",
    "Viva / Oral Defence": "ability to explain and justify the work when questioned",
    "Collaboration & Teamwork": "contribution to shared work and responsibility",
}

_CRITERION_QUALITY: List[Tuple[str, str, str]] = [
    ("Perceptive", "Excellent", "Thorough, accurate and consistent"),
    ("Clear", "Good", "Clear and largely accurate"),
    ("Generally Clear", "Fair", "Generally sound, with minor gaps"),
    ("Straightforward", "Needs Improvement", "Partial, with notable gaps"),
    ("Limited", "Beginning", "Minimal"),
]


def build_criterion_descriptors(criterion: str, weight_marks: int) -> List[dict]:
    """Build the level descriptors for one analytical criterion."""
    levels = max(2, min(level_count_for_marks(weight_marks) or 2, 5))
    focus = CRITERION_FOCUS.get(criterion, "performance against this criterion")
    rungs = _CRITERION_QUALITY[:levels]
    bands = _mark_bands(weight_marks, levels)

    descriptors: List[dict] = []
    for offset, (quality, label, adjective) in enumerate(rungs):
        low, high = bands[levels - 1 - offset]
        descriptors.append({
            "level": levels - offset,
            "quality_band": quality,
            "display_label": label,
            "descriptors": [f"{adjective} {focus}."],
            "mark_low": low,
            "mark_high": high,
        })

    descriptors.append({
        "level": 0,
        "quality_band": "Nothing to Reward",
        "display_label": "No Credit",
        "descriptors": ["Nothing to reward"],
        "mark_low": 0,
        "mark_high": 0,
    })
    return descriptors
