"""Concepts: generated by the Chapter Queue, enriched by the Concept Queue.

The module has two halves, and the split is the point of it.

GENERATION -- generate_concepts(), called only by chapter_pipeline. ONE prompt
sees the whole chapter, every topic, and the curriculum, and returns each
topic's concepts with a name, a short description, an evidence quote and the
curriculum codes it serves. How many it may return is decided BEFORE the call by
concept_budget, from the syllabus and the timetable, and enforced AFTER it by
the same module.

That budget is why this file exists in its present form. The count used to come
from `len(md_content)` at 0.8-1.8 concepts per thousand characters, so a
61k-character chapter was told in prompt rule 4 that it "normally yields between
49 and 110 concepts" -- and returned 37 distinct ones across six topics, with
nothing in code able to say that was too many. The cap was prompt text and a log
line. It is now an allowance per topic in the prompt and a ranked trim in code.

ENRICHMENT -- process_concepts_by_id(), the Concept Queue's own button. It reads
the concepts that already exist and fills in the three teaching fields:
definition, mastery_threshold, estimated_mastery_minutes. It NEVER inserts a
concept and never deletes one. That is not a style preference: lms_concept.id is
referenced by lms_question_master, lms_question_extraction,
lms_lesson_plan_concepts and lms_lesson_plan_periods, and the delete-then-insert
this path used to perform has already orphaned 213 rows across those tables on
this database.

Generation writes through the same guarantee, by retiring rows
(concept_show_hide = 0) and upserting on ct.match_key(name) -- exactly what
topic_master has always done, and for exactly the same reason.

The hierarchy is unchanged:

    Chapter -> Topics -> Concepts

so both halves depend on topic_master. chapter_master.key_concepts is still
written, but derived from these rows rather than generated separately, so the
two vocabularies can no longer disagree.
"""

import asyncio
import json
import logging
import re
from typing import Any, Dict, List

from sqlalchemy import text
from sqlalchemy.exc import OperationalError

from app.db.mariadb import SessionLocal
# A provider fault (billing, auth, unknown model) is not caught here. With a
# single call there is nothing to salvage, so it propagates to the route, which
# turns it into a 503 naming the actual cause.
from app.semantic_intelligence.deepseek_client import async_call_deepseek
from app.services import chapter_text as ct
from app.services import concept_budget
from app.services import confidence as cs
from app.services import curriculum_frame as curf
from app.services import extraction_schema
from app.services.concept_budget import Budget

logger = logging.getLogger(__name__)

# Retries for the post-run write, for the same reason as the Topic Queue: the
# call runs for minutes and a stale pooled connection must not throw away it.
_PERSIST_ATTEMPTS = 4
_PERSIST_BACKOFF_SEC = 3

_DEFAULT_TOPIC_MINUTES = 20


CONCEPT_PROMPT = """You are an expert instructional designer and educational content analyst. You work across every school board (CBSE/NCERT, Cambridge, ICSE, IB and state boards), standards 1 to 12, and every subject including Hindi, Gujarati, English, Sanskrit, Mathematics, Science, Social Science, History, Geography, Civics, Biology, Chemistry, Physics and Computer Science.

You are given a COMPLETE chapter and the list of main topics it has already been divided into. Your task is to break EVERY listed topic into the individual CONCEPTS a learner must master to be competent in it, and to assign each concept a scientifically-backed mastery threshold and learning time. This data is used directly for teacher and student training in schools, so precision and pedagogical methodology are critical. Return ONLY a valid JSON object. No explanation, no markdown, no preamble, no trailing text.

Rules you must follow:

1. COVER EVERY TOPIC. Return one entry per topic in `Topics To Process`, in the same order, with `topic_name` copied EXACTLY as given. Never skip a topic, never invent one, never merge two. `Chapter Topics` lists the chapter's full topic list so you can see the boundaries: a topic's material runs from where that topic begins until the next one begins.

2. WHAT A CONCEPT IS. A concept is a single masterable idea a learner either knows or does not: a definition, a law or formula, a relationship, a procedure, a distinction between two things, a grammar rule, a literary device, a cause-effect link. It is NOT a classroom activity, NOT an exercise question, and NOT a restatement of the whole topic.
   Test it: for the topic "Adding and subtracting integers", "Adding integers with different signs" is a concept. "Adding integers" is not — that is just the topic again in fewer words.

3. HOW MANY PER TOPIC. Every topic in `Topics To Process` carries a `[Concepts: N]` allowance. Return exactly N for that topic, or N-1 or N+1 where the material genuinely demands it. The allowance is not a minimum to pad up to and not a maximum to fill: if a topic honestly teaches fewer distinct masterable ideas than its allowance, return fewer and say so by simply returning fewer.
   These numbers are not arbitrary. They come from how many periods the syllabus allots this chapter and how many learning outcomes it must deliver, divided across topics by how much of the chapter each one covers.

4. HOW MANY IN TOTAL. The allowances add up to {target_concepts} concepts for this chapter, and the whole chapter should land between {min_concepts} and {max_concepts}. Going far beyond that means you are splitting below the concept level — each entry has stopped being a masterable idea and become a single sentence from the book. A learner cannot master more than about two genuinely new ideas in a 40-minute period, so a chapter taught in a dozen periods does not contain fifty of them.

5. NO DUPLICATES ANYWHERE. You can see every topic at once, so this is your responsibility, not a later cleanup. The same idea must appear under exactly ONE topic. If two topics could both claim a concept, give it to the topic that teaches it FIRST and leave it out of the other. Two concepts must never describe the same idea in different words, whether they sit under the same topic or different ones.

6. ADAPT TO THE LEVEL:
   - Std 1-5 (Primary): simple terms, basic ideas, foundational vocabulary
   - Std 6-8 (Middle): definitions, processes, relationships between ideas
   - Std 9-10 (Secondary): principles, laws, theories, formulas, cause-effect
   - Std 11-12 (Higher Secondary): advanced theories, derivations, analytical concepts

7. CRITICAL INSTRUCTION: ALL extracted text (Concept Names AND Descriptions) MUST strictly remain in the ORIGINAL script/language (e.g., Sanskrit, Hindi, Gujarati, Marathi) found in the chapter content. DO NOT translate any text into English. Only the JSON keys must be in English.

8. `name` must be concise (2 to 6 words). `description` must be 1 to 2 sentences max.

9. Assign every concept an `estimated_mastery_minutes` (integer) using Cognitive Load Theory and Bloom's Taxonomy. Within EACH topic, the minutes of that topic's concepts MUST add up to approximately that topic's `Minutes` budget given below. Distribute each budget by cognitive load:
   - Remembering / identifying / defining: the smallest share
   - Understanding / applying / solving basic problems: a medium share
   - Analyzing / evaluating / derivations / multi-step problem solving: the largest share

10. GROUNDING: every concept MUST come from the `Chapter Content` below, and from the part of it that belongs to its own topic. For each concept, `source_evidence` must contain one EXACT quote of 5 to 10 words copied character-for-character from the chapter. Do not paraphrase the quote. Do not invent concepts the chapter does not support.

11. THE CURRICULUM. `Curriculum Outcomes` below lists what the syllabus requires of this chapter, each with a code. For every concept, `curriculum_codes` must list the codes that concept helps a learner achieve — usually one, at most three, and an empty list where the chapter teaches something the syllabus does not name. Cite ONLY codes that appear in that list, copied exactly. Never invent a code, and never cite one because it sounds related: a wrong code reads as curriculum alignment and is worse than none.
    Where the curriculum block says nothing is loaded, return an empty list for every concept.

12. Output ONLY the JSON object. No other text.

Return the JSON in the following format:
{
  "topics": [
    {
      "topic_name": "Exactly the topic name as given to you",
      "concepts": [
        {
          "name": "Concept Name",
          "description": "Concept Description",
          "estimated_mastery_minutes": 15,
          "source_evidence": "exact quote from the chapter content",
          "curriculum_codes": ["C-3.1-LO-2"]
        }
      ]
    }
  ]
}

Board: {board}
Standard: {standard}
Subject: {subject_name}
Chapter Name: {chapter_name}
Chapter Length: {chapter_chars} characters

Chapter Topics (the full list, in teaching order):
{chapter_outline}

Curriculum Outcomes (cite these codes in `curriculum_codes`):
{curriculum_block}

Topics To Process (produce concepts for every one of these):
{topic_table}

Chapter Content (this is the COMPLETE chapter):
{chapter_content}
"""

SYSTEM_PROMPT = "You are a helpful assistant. Return ONLY a JSON object."

# Substituted in a single pass so a value can never be rescanned as a
# placeholder, and so the literal braces of the JSON example survive untouched
# (which is also why this prompt is not an f-string).
_PLACEHOLDER_RE = re.compile(
    r"\{(board|standard|subject_name|chapter_name|chapter_chars|chapter_outline"
    r"|curriculum_block|topic_table|chapter_content"
    r"|min_concepts|max_concepts|target_concepts)\}"
)


def _fill(template: str, values: Dict[str, str]) -> str:
    return _PLACEHOLDER_RE.sub(lambda m: values.get(m.group(1), ""), template)


# ---------------------------------------------------------------------------
# Deterministic post-pass: coercion, thresholds, dedupe
# ---------------------------------------------------------------------------

# lms_concept.mastery_threshold is a percentage; the rubric in rule 7 never
# licenses anything outside this band, so a model that answers 0 or 120 is
# clamped rather than written through.
_MIN_THRESHOLD = 50
_MAX_THRESHOLD = 100
_DEFAULT_THRESHOLD = 80


def _clean_concepts(raw_concepts: Any) -> List[Dict[str, Any]]:
    """Coerce the model's list into well-formed concept dicts, dropping junk."""
    if not isinstance(raw_concepts, list):
        return []

    cleaned: List[Dict[str, Any]] = []
    for item in raw_concepts:
        if not isinstance(item, dict):
            continue
        name = str(item.get("name") or "").strip()
        if not name:
            continue
        codes = item.get("curriculum_codes")
        if isinstance(codes, str):
            # The model answers with a bare string often enough that rejecting
            # it would lose real citations over punctuation.
            codes = [codes]
        # lms_concept.name is VARCHAR(191).
        cleaned.append({
            "name": name[:191],
            "description": str(item.get("description") or "").strip(),
            "estimated_mastery_minutes": max(
                1, ct.safe_int(item.get("estimated_mastery_minutes"), 15) or 15
            ),
            # lms_concept.source_evidence is VARCHAR(512).
            "source_evidence": str(item.get("source_evidence") or "").strip()[:512],
            "curriculum_codes": [str(c) for c in codes if c] if isinstance(codes, list) else [],
            # mastery_threshold is no longer asked for here: the enrichment
            # stage sets it against the full definition, which is a far better
            # basis than a name and one line. 0.00 is the "not yet enriched"
            # sentinel, because the column is NOT NULL and owned by the ERP.
            "mastery_threshold": 0,
        })

    return cleaned


def _dedupe_across_topics(results: List[Dict[str, Any]]) -> int:
    """Drop a concept that a later topic repeats; the earlier topic keeps it.

    A safety net, not the primary mechanism. Rule 5 makes cross-topic
    de-duplication the model's job now that one call sees every topic at once,
    which it can do far better than name matching -- it knows two differently
    worded entries mean the same idea. This catches what slips through. Results
    must already be in chapter teaching order.

    Matching is by token containment, not exact name, and a topic is never
    stripped bare: a childless topic breaks the hierarchy, which is worse than
    keeping one near-duplicate concept under it.
    """
    return ct.dedupe_by_name(results, "concepts", "name", keep_at_least_one=True)


# ---------------------------------------------------------------------------
# LLM: one master prompt, the whole chapter, every topic at once
# ---------------------------------------------------------------------------

def _topic_table(topics: List[Dict[str, Any]], quota: List[int] | None = None) -> str:
    """The topics this call must return concepts for, with their allowances.

    The per-topic concept allowance is the single most effective control in this
    prompt. A chapter-wide range leaves the model to divide the total itself,
    which is how "3 to 10 per topic" across six topics became a licence for
    anything up to sixty; an integer per topic leaves nothing to interpret.
    """
    lines = []
    for order, topic in enumerate(topics, start=1):
        minutes = ct.safe_int(topic.get("estimated_minutes"), _DEFAULT_TOPIC_MINUTES) or _DEFAULT_TOPIC_MINUTES
        description = (topic.get("description") or "").strip()
        allowance = ""
        if quota and order - 1 < len(quota):
            allowance = f"  [Concepts: {quota[order - 1]}]"
        lines.append(f"{order}. {topic['name']}  [Minutes: {minutes}]{allowance}")
        if description:
            lines.append(f"     {description}")
    return "\n".join(lines)


def _chapter_outline(topics: List[Dict[str, Any]]) -> str:
    return "\n".join(f"{order}. {t['name']}" for order, t in enumerate(topics, start=1))


def _match_returned_topics(
    returned: Any,
    targets: List[Dict[str, Any]],
) -> tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Line the model's answer back up with the topics we asked about.

    Matching is by name rather than by position: a model that drops or reorders
    a topic would otherwise have every subsequent topic's concepts filed under
    the wrong parent, which is silent and much worse than a missing topic.
    Position is the fallback only when the count came back exactly right.
    """
    blocks = returned if isinstance(returned, list) else []
    by_key: Dict[str, Any] = {}
    for block in blocks:
        if isinstance(block, dict):
            by_key.setdefault(ct.match_key(str(block.get("topic_name") or "")), block)

    results: List[Dict[str, Any]] = []
    missing: List[Dict[str, Any]] = []
    for index, topic in enumerate(targets):
        block = by_key.get(ct.match_key(topic["name"]))
        if block is None and len(blocks) == len(targets) and isinstance(blocks[index], dict):
            block = blocks[index]

        budget = ct.safe_int(topic.get("estimated_minutes"), _DEFAULT_TOPIC_MINUTES) or _DEFAULT_TOPIC_MINUTES
        concepts = _clean_concepts((block or {}).get("concepts"))
        if not concepts:
            missing.append({
                "topic_id": topic["id"],
                "topic_name": topic["name"],
                "error": "the model returned no concepts for this topic",
            })
            continue
        results.append({
            "topic_id": topic["id"],
            "topic_name": topic["name"],
            "topic_minutes": budget,
            "concepts": concepts,
        })
    return results, missing


async def _extract_concepts(
    *,
    md_content: str,
    targets: List[Dict[str, Any]],
    all_topics: List[Dict[str, Any]],
    chapter_name: str,
    subject_name: str,
    standard: Any,
    board: Any,
    budget: Budget,
    curriculum_block: str = "",
) -> Dict[str, Any]:
    """Ask once, about the entire chapter and every topic in it.

    targets is normally all_topics. A single-topic retry narrows it to one, but
    still sends the whole chapter and the full outline, because the point of
    this design is that the model always sees what it is dividing.
    """
    # The allowance follows the topic, not its position, so a narrowed retry
    # still hands each target the share the whole-chapter plan gave it.
    quota_by_id = {
        topic["id"]: budget.quota[index]
        for index, topic in enumerate(all_topics)
        if index < len(budget.quota)
    }
    target_quota = [
        quota_by_id.get(topic["id"], concept_budget.MIN_PER_TOPIC) for topic in targets
    ]

    prompt = _fill(CONCEPT_PROMPT, {
        "board": str(board or "").strip() or "(not specified)",
        "standard": str(standard or ""),
        "subject_name": str(subject_name or ""),
        "chapter_name": str(chapter_name or ""),
        "chapter_chars": str(len(md_content)),
        "chapter_outline": _chapter_outline(all_topics),
        "curriculum_block": curriculum_block or "(no curriculum is loaded for this subject)",
        "topic_table": _topic_table(targets, target_quota),
        "chapter_content": md_content,
        "min_concepts": str(budget.low),
        "max_concepts": str(budget.high),
        "target_concepts": str(sum(target_quota) or budget.target),
    })

    result = await async_call_deepseek(
        prompt,
        system_prompt=SYSTEM_PROMPT,
        response_format={"type": "json_object"},
    )
    data = result.get("data") or {}
    if not isinstance(data, dict):
        data = {}

    results, missing = _match_returned_topics(data.get("topics"), targets)

    for entry in results:
        ct.normalise_minutes(entry["concepts"], "estimated_mastery_minutes", entry["topic_minutes"])
        # Grounded against the whole chapter, which is what the model was shown.
        ct.verify_grounding(entry["concepts"], md_content)

    return {
        "results": results,
        "missing": missing,
        "concept_budget": budget.as_dict(),
        "input_tokens": result.get("input_tokens", 0),
        "output_tokens": result.get("output_tokens", 0),
    }


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

_CONCEPT_COLUMNS = (
    "source_evidence", "evidence_verified", "confidence", "confidence_profile",
    "confidence_parts", "review_status", "concept_show_hide",
)

_INSERT_CONCEPT = text("""
    INSERT INTO lms_concept (
        extraction_id, topic_id, name, description, standard_id, subject_id,
        chapter_id, sub_institute_id, mastery_threshold,
        estimated_mastery_minutes, syear, created_at, updated_at
    ) VALUES (
        :extraction_id, :topic_id, :name, :description, :standard_id, :subject_id,
        :chapter_id, :sub_institute_id, :mastery_threshold,
        :estimated_mastery_minutes, :syear, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    )
""")

_INSERT_CONCEPT_SCORED = text("""
    INSERT INTO lms_concept (
        extraction_id, topic_id, name, description, standard_id, subject_id,
        chapter_id, sub_institute_id, mastery_threshold,
        estimated_mastery_minutes, syear, source_evidence, evidence_verified,
        confidence, confidence_profile, confidence_parts, review_status,
        concept_show_hide, created_at, updated_at
    ) VALUES (
        :extraction_id, :topic_id, :name, :description, :standard_id, :subject_id,
        :chapter_id, :sub_institute_id, :mastery_threshold,
        :estimated_mastery_minutes, :syear, :source_evidence, :evidence_verified,
        :confidence, :confidence_profile, :confidence_parts, :review_status,
        1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    )
""")

# The upsert keeps the row, and therefore the id that four other tables point
# at. description is refreshed because Semantic Intelligence reads it;
# mastery_threshold and definition are NOT, because the enrichment stage owns
# them and a re-run of generation must not wipe work that stage has done.
_UPDATE_CONCEPT = text("""
    UPDATE lms_concept
       SET topic_id = :topic_id,
           description = :description,
           estimated_mastery_minutes = :estimated_mastery_minutes,
           chapter_id = :chapter_id,
           extraction_id = :extraction_id,
           updated_at = CURRENT_TIMESTAMP
     WHERE id = :id
""")

_UPDATE_CONCEPT_SCORED = text("""
    UPDATE lms_concept
       SET topic_id = :topic_id,
           description = :description,
           estimated_mastery_minutes = :estimated_mastery_minutes,
           chapter_id = :chapter_id,
           extraction_id = :extraction_id,
           source_evidence = :source_evidence,
           evidence_verified = :evidence_verified,
           confidence = :confidence,
           confidence_profile = :confidence_profile,
           confidence_parts = :confidence_parts,
           review_status = :review_status,
           concept_show_hide = 1,
           updated_at = CURRENT_TIMESTAMP
     WHERE id = :id
""")

_RETIRE_CONCEPT = text("""
    UPDATE lms_concept
       SET concept_show_hide = 0, updated_at = CURRENT_TIMESTAMP
     WHERE id = :id
""")


def _persist_concepts(
    *,
    extraction_id: int,
    chapter_id: int,
    standard_id: Any,
    subject_id: Any,
    sub_institute_id: Any,
    syear: Any,
    results: List[Dict[str, Any]],
    topic_id: int | None,
) -> Dict[str, int]:
    """Upsert this extraction's concepts, retiring the ones that no longer apply.

    This used to DELETE every row of the extraction and INSERT fresh ones, which
    changed every lms_concept.id on every run. Those ids are referenced by
    lms_question_master, lms_question_extraction, lms_lesson_plan_concepts and
    lms_lesson_plan_periods, and on this database the churn has already stranded
    132 lesson-plan concepts, 60 period rows and 21 question rows. Two
    overlapping runs also each deleted and each inserted, which is why 16
    chapters here hold every concept exactly twice.

    So the natural key is (extraction_id, match_key(name)), the same one
    topic_master has always used, and a concept that disappears from a re-run is
    hidden rather than removed. Scope is as tight as the run: a single-topic
    retry never touches a sibling topic's rows.
    """
    with SessionLocal() as db:
        scored = extraction_schema.supports(db, "lms_concept", *_CONCEPT_COLUMNS)
        insert_sql = _INSERT_CONCEPT_SCORED if scored else _INSERT_CONCEPT
        update_sql = _UPDATE_CONCEPT_SCORED if scored else _UPDATE_CONCEPT

        where_topic = " AND topic_id = :topic_id" if topic_id is not None else ""
        params: Dict[str, Any] = {"extraction_id": extraction_id}
        if topic_id is not None:
            params["topic_id"] = topic_id

        existing = db.execute(
            text(
                "SELECT id, name FROM lms_concept "
                "WHERE extraction_id = :extraction_id" + where_topic
            ),
            params,
        ).mappings().fetchall()

        by_name: Dict[str, Any] = {}
        for row in existing:
            key = ct.match_key(row["name"])
            # Lowest id wins, so a run that follows the duplicate-row bug
            # collapses onto the original rather than the copy.
            if key and key not in by_name:
                by_name[key] = row["id"]

        inserted = updated = 0
        touched: set[int] = set()
        for result in results:
            for concept in result["concepts"]:
                row_params = {
                    "extraction_id": extraction_id,
                    "topic_id": result["topic_id"],
                    "name": concept["name"],
                    "description": concept["description"],
                    "standard_id": standard_id,
                    "subject_id": subject_id,
                    "chapter_id": chapter_id,
                    "sub_institute_id": sub_institute_id,
                    "mastery_threshold": concept.get("mastery_threshold") or 0,
                    "estimated_mastery_minutes": concept["estimated_mastery_minutes"],
                    "syear": syear,
                }
                if scored:
                    row_params.update({
                        "source_evidence": (concept.get("source_evidence") or "")[:512],
                        "evidence_verified": 1 if concept.get("evidence_verified") else 0,
                        "confidence": concept.get("confidence"),
                        "confidence_profile": concept.get("confidence_profile"),
                        "confidence_parts": json.dumps(
                            concept.get("confidence_parts") or {}, ensure_ascii=False
                        ),
                        "review_status": concept.get("review_status") or cs.STATUS_ACCEPTED,
                    })

                match = by_name.get(ct.match_key(concept["name"]))
                if match:
                    db.execute(update_sql, {**row_params, "id": match})
                    concept["concept_id"] = match
                    updated += 1
                else:
                    concept["concept_id"] = db.execute(insert_sql, row_params).lastrowid
                    inserted += 1
                touched.add(concept["concept_id"])

        retired = 0
        if scored:
            for row in existing:
                if row["id"] not in touched:
                    db.execute(_RETIRE_CONCEPT, {"id": row["id"]})
                    retired += 1

        db.commit()
        # `deleted` is kept in the payload under its old name so the queue UI's
        # existing chip keeps working; nothing is deleted any more.
        return {"inserted": inserted, "updated": updated,
                "retired": retired, "deleted": 0}


async def _persist_with_retry(write: Any, extraction_id: int) -> Dict[str, int]:
    """Run a synchronous write off the event loop, retrying transient DB faults."""
    last_error: OperationalError | None = None
    for attempt in range(_PERSIST_ATTEMPTS):
        try:
            return await asyncio.to_thread(write)
        except OperationalError as exc:
            last_error = exc
            if attempt == _PERSIST_ATTEMPTS - 1:
                break
            delay = _PERSIST_BACKOFF_SEC * (2 ** attempt)
            logger.warning(
                "Concept persistence attempt %s/%s for extraction %s failed (%s); retrying in %ss",
                attempt + 1, _PERSIST_ATTEMPTS, extraction_id, exc.orig, delay,
            )
            await asyncio.sleep(delay)

    raise RuntimeError(
        f"Concepts for extraction {extraction_id} were generated but could not "
        f"be saved after {_PERSIST_ATTEMPTS} attempts. The LLM output was lost; re-run once "
        f"the database is reachable. Last error: {last_error}"
    ) from last_error


# ---------------------------------------------------------------------------
# Generation -- called by chapter_pipeline, not by any route
# ---------------------------------------------------------------------------

async def generate_concepts(
    *,
    extraction_id: int,
    md_content: str,
    all_topics: List[Dict[str, Any]],
    budget: Budget,
    frame: curf.CurriculumFrame,
    chapter_name: str,
    subject_name: Any = None,
    standard: Any = None,
    board: Any = None,
    targets: List[Dict[str, Any]] | None = None,
) -> Dict[str, Any]:
    """One whole-chapter call, then the deterministic passes that bound it.

    Nothing is persisted here and no database session is held, because the
    caller owns both: this runs as one stage of a longer job, and a session left
    open across the minutes this call takes is how the other services came to
    need connection-retry wrappers.
    """
    targets = targets if targets is not None else all_topics

    extracted = await _extract_concepts(
        md_content=md_content,
        targets=targets,
        all_topics=all_topics,
        chapter_name=chapter_name,
        subject_name=subject_name,
        standard=standard,
        board=board,
        budget=budget,
        curriculum_block=frame.prompt_block(),
    )

    failed = extracted["missing"]
    # Chapter teaching order, so the dedupe below keeps the occurrence in the
    # topic that teaches it first.
    order = {t["id"]: i for i, t in enumerate(all_topics)}
    results = sorted(extracted["results"], key=lambda r: order.get(r["topic_id"], 0))

    if not results:
        raise RuntimeError(
            f"Concept extraction produced nothing for extraction {extraction_id}: the model "
            f"returned no concepts for any of the {len(targets)} topic(s) it was given. "
            f"Check the backend log for the raw response."
        )

    duplicates_dropped = _dedupe_across_topics(results)

    # The cap, finally enforced rather than suggested. Ranks each topic's
    # concepts on the evidence behind them and trims the weakest back to the
    # allowance -- but a grounded concept outscores the quality bar, so a
    # chapter that genuinely earns more than its target keeps them.
    trimmed = concept_budget.enforce_quota(
        results, budget,
        md_content=md_content,
        outline_text=_chapter_outline(all_topics),
        outcome_text=frame.anchor_text(),
    )

    # Re-scaled AFTER the dedupe and the trim, not before. _extract_concepts
    # already scaled each topic to its budget, so dropping a concept afterwards
    # leaves the survivors summing to less than it -- one topic came back at 5
    # minutes against a 20 minute budget that way.
    for result in results:
        ct.normalise_minutes(result["concepts"], "estimated_mastery_minutes",
                             result["topic_minutes"])

    _score_and_map(results, md_content=md_content, all_topics=all_topics, frame=frame)

    total = sum(len(r["concepts"]) for r in results)
    grounded = sum(1 for r in results for c in r["concepts"] if c.get("evidence_verified"))
    return {
        "results": results,
        "failed_topics": failed,
        "concepts_extracted": total,
        "concept_budget": extracted["concept_budget"],
        "duplicates_dropped": duplicates_dropped,
        "trimmed": trimmed,
        "grounded_concepts": grounded,
        "ungrounded_concepts": total - grounded,
        "input_tokens": extracted["input_tokens"],
        "output_tokens": extracted["output_tokens"],
    }


def _score_and_map(
    results: List[Dict[str, Any]],
    *,
    md_content: str,
    all_topics: List[Dict[str, Any]],
    frame: curf.CurriculumFrame,
) -> None:
    """Attach a confidence score and curriculum mappings to every concept.

    Both are measured, never asked for. The curriculum codes the model cited are
    validated against the chapter's real frame first -- a code this curriculum
    does not contain reads as alignment and is worse than none -- and anything
    it failed to cite falls back to the lexical matcher, whose scores are capped
    so a keyword hit can never look like comprehension.
    """
    profile = cs.profile_for(curriculum_usable=frame.is_usable)
    spans = ct.partition_by_topics(md_content, [t["name"] for t in all_topics])
    span_by_topic = {t["id"]: s for t, s in zip(all_topics, spans)}
    outcome_stems = ct.stems(frame.anchor_text()) if frame.is_usable else None

    every_name = [c["name"] for r in results for c in r["concepts"]]
    lexical = curf.match_concepts(
        [c for r in results for c in r["concepts"]], frame
    ) if frame.is_usable else {}

    for result in results:
        span = span_by_topic.get(result["topic_id"], (0, len(md_content)))
        slice_stems = ct.stems(md_content[span[0]:span[1]])
        for concept in result["concepts"]:
            cited = curf.sanitise_codes(concept.get("curriculum_codes"), frame)
            mappings = cited or lexical.get(id(concept)) or []
            concept["curriculum_mappings"] = mappings

            score = cs.score_concept(
                concept,
                profile=profile,
                md_content=md_content,
                span=span,
                slice_stems=slice_stems,
                siblings=[n for n in every_name if n != concept["name"]],
                outcome_stems=outcome_stems,
                mapped_outcomes=mappings,
                curriculum_available=frame.is_usable,
            )
            concept["confidence"] = score.value
            concept["confidence_profile"] = score.profile
            concept["confidence_parts"] = score.parts
            concept["review_status"] = score.status


def persist_concepts(**kwargs: Any) -> Dict[str, int]:
    """Public entry to the upsert, for chapter_pipeline."""
    return _persist_concepts(**kwargs)


# ---------------------------------------------------------------------------
# Enrichment -- the Concept Queue's own button
# ---------------------------------------------------------------------------

ENRICH_PROMPT = """You are an expert instructional designer writing the teaching definition of each concept a chapter covers. You work across every school board (CBSE/NCERT, Cambridge, ICSE, IB and state boards), standards 1 to 12, and every subject including Hindi, Gujarati, English, Sanskrit, Mathematics, Science, Social Science, History, Geography, Civics, Biology, Chemistry, Physics and Computer Science.

The concepts already exist. You are NOT deciding what they are, NOT adding new ones, and NOT removing any. You are filling in three fields for each one, and you must return exactly one entry for every `concept_id` given to you, echoing that id unchanged. This data drives teacher and student training in schools, so precision and pedagogical methodology are critical. Return ONLY a valid JSON object. No explanation, no markdown, no preamble, no trailing text.

For each concept:

1. `definition` — the full teaching definition a teacher would give and a learner would be assessed against: 2 to 4 sentences. State what the concept IS, the condition or rule that governs it, and where it applies. Include the formula, law or exact wording where the chapter gives one. This is longer and more precise than the one-line description you are shown; do not simply repeat that back.

2. `mastery_threshold` — an integer percentage, the score at which a learner should be considered to have mastered this concept. Use this rubric strictly:
   - 90 to 95: Foundational and prerequisite concepts (crucial for future learning; basic formulas, core definitions)
   - 80 to 85: Core/standard concepts (main syllabus content; application of knowledge)
   - 70 to 75: Advanced/enrichment concepts (high-level synthesis, complex analysis, abstract theory where perfection is rare)
   Judge from the concept itself, not from its position in the list. A chapter has more core concepts than foundational ones.

3. `estimated_mastery_minutes` — an integer, the classroom time to take a learner to that threshold, by Cognitive Load Theory and Bloom's Taxonomy:
   - Remembering / identifying / defining: the smallest share
   - Understanding / applying / solving basic problems: a medium share
   - Analyzing / evaluating / derivations / multi-step problem solving: the largest share
   Within each topic these must add up to approximately that topic's `Minutes` budget.

4. CRITICAL INSTRUCTION: ALL text MUST stay in the ORIGINAL script/language of the chapter (e.g. Sanskrit, Hindi, Gujarati, Marathi). DO NOT translate into English. Only the JSON keys are in English.

5. Output ONLY the JSON object. No other text.

Return the JSON in the following format:
{
  "concepts": [
    {
      "concept_id": 1234,
      "definition": "The full teaching definition, 2 to 4 sentences.",
      "mastery_threshold": 85,
      "estimated_mastery_minutes": 12
    }
  ]
}

Board: {board}
Standard: {standard}
Subject: {subject_name}
Chapter Name: {chapter_name}

Concepts To Enrich (one entry per concept_id, grouped by their topic):
{concept_table}

Chapter Content (this is the COMPLETE chapter):
{chapter_content}
"""

_ENRICH_PLACEHOLDER_RE = re.compile(
    r"\{(board|standard|subject_name|chapter_name|concept_table|chapter_content)\}"
)

_UPDATE_ENRICHMENT = text("""
    UPDATE lms_concept
       SET definition = :definition,
           mastery_threshold = :mastery_threshold,
           estimated_mastery_minutes = :estimated_mastery_minutes,
           enriched_at = CURRENT_TIMESTAMP,
           updated_at = CURRENT_TIMESTAMP
     WHERE id = :id
""")

# Without the definition column the stage has nothing to add that generation has
# not already written, so it degrades to refreshing the two numeric fields.
_UPDATE_ENRICHMENT_BASIC = text("""
    UPDATE lms_concept
       SET mastery_threshold = :mastery_threshold,
           estimated_mastery_minutes = :estimated_mastery_minutes,
           updated_at = CURRENT_TIMESTAMP
     WHERE id = :id
""")


def _concept_table(groups: List[Dict[str, Any]]) -> str:
    lines: List[str] = []
    for group in groups:
        minutes = group.get("topic_minutes") or _DEFAULT_TOPIC_MINUTES
        lines.append(f"Topic: {group['topic_name']}  [Minutes: {minutes}]")
        for concept in group["concepts"]:
            lines.append(f"  concept_id={concept['id']}: {concept['name']}")
            description = (concept.get("description") or "").strip()
            if description:
                lines.append(f"      (current one-line description: {description})")
    return "\n".join(lines)


def _clean_enrichment(payload: Any, valid_ids: set[int]) -> Dict[int, Dict[str, Any]]:
    """Index the model's answer by concept_id, dropping ids it invented.

    An id that is not in this chapter means the model answered about something
    else; writing it would overwrite an unrelated concept, possibly in another
    chapter. Same guard, for the same reason, as question_ai_tagger._sanitise.
    """
    out: Dict[int, Dict[str, Any]] = {}
    for item in (payload or {}).get("concepts", []) or []:
        if not isinstance(item, dict):
            continue
        concept_id = ct.safe_int(item.get("concept_id"))
        if concept_id is None or concept_id not in valid_ids:
            if concept_id is not None:
                logger.warning("Dropping enrichment for unknown concept_id %s", concept_id)
            continue
        threshold = ct.safe_int(item.get("mastery_threshold"), _DEFAULT_THRESHOLD) or _DEFAULT_THRESHOLD
        out[concept_id] = {
            "definition": str(item.get("definition") or "").strip(),
            "mastery_threshold": min(_MAX_THRESHOLD, max(_MIN_THRESHOLD, threshold)),
            "estimated_mastery_minutes": max(
                1, ct.safe_int(item.get("estimated_mastery_minutes"), 15) or 15
            ),
        }
    return out


async def process_concepts_by_id(
    extraction_id: int,
    force: bool = False,
    topic_id: int | None = None,
) -> Dict[str, Any]:
    """Fill in definition, mastery threshold and mastery minutes. Nothing else.

    This stage cannot create a concept and cannot remove one. The concepts come
    from the Chapter Queue, which decides what they are against the curriculum
    and the chapter together; this decides how each one is taught and assessed.

    It is also the reason lms_concept.id is now stable: the delete-then-insert
    this function used to perform is what orphaned 213 rows in the question bank
    and the lesson planner.
    """
    with SessionLocal() as db:
        row = db.execute(
            text("SELECT * FROM document_extractions WHERE id = :id"),
            {"id": extraction_id},
        ).mappings().fetchone()
        if not row:
            raise ValueError(f"No document_extraction found for id {extraction_id}")

        has_definition = extraction_schema.supports(db, "lms_concept", "definition", "enriched_at")
        visible = " AND COALESCE(c.concept_show_hide, 1) = 1" if extraction_schema.supports(
            db, "lms_concept", "concept_show_hide"
        ) else ""
        scope = " AND c.topic_id = :topic_id" if topic_id is not None else ""
        params: Dict[str, Any] = {"id": extraction_id}
        if topic_id is not None:
            params["topic_id"] = topic_id

        rows = [dict(r) for r in db.execute(
            text(f"""
                SELECT c.id, c.name, c.description, c.topic_id,
                       {'c.enriched_at,' if has_definition else 'NULL AS enriched_at,'}
                       t.name AS topic_name, t.estimated_minutes AS topic_minutes,
                       t.topic_sort_order
                  FROM lms_concept c
             LEFT JOIN topic_master t ON t.id = c.topic_id
                 WHERE c.extraction_id = :id{visible}{scope}
              ORDER BY COALESCE(t.topic_sort_order, 0) ASC, c.id ASC
            """),
            params,
        ).mappings().fetchall()]

        if not rows:
            # Deliberately not an exception. "There is nothing to enrich yet" is
            # a normal state for a chapter the Chapter Queue has not run, and the
            # queue UI shows it as "Need Chapter" rather than an error.
            return {
                "status": "no_concepts",
                "action": "skipped",
                "extraction_id": extraction_id,
                "message": "This chapter has no concepts yet. Run the Chapter queue first.",
            }

        if not force and all(r.get("enriched_at") for r in rows):
            return {
                "status": "already_processed",
                "action": "skipped",
                "message": "Concepts already enriched. Skipped to save LLM tokens.",
                **(get_concept_data_by_extraction_id(extraction_id) or {}),
            }

        md_content = row.get("md_content") or ""
        if not md_content:
            raise ValueError(f"document_extraction {extraction_id} has no md_content")

        chapter_name = row.get("document_tittle") or ""
        subject_name = row.get("subject_name")
        standard = row.get("standard")
        board = row.get("board")

    groups: List[Dict[str, Any]] = []
    index: Dict[Any, Dict[str, Any]] = {}
    for record in rows:
        bucket = index.get(record["topic_id"])
        if bucket is None:
            bucket = {
                "topic_id": record["topic_id"],
                "topic_name": record["topic_name"] or "Unassigned (chapter-wise)",
                "topic_minutes": record["topic_minutes"],
                "concepts": [],
            }
            index[record["topic_id"]] = bucket
            groups.append(bucket)
        bucket["concepts"].append(record)

    prompt = _ENRICH_PLACEHOLDER_RE.sub(
        lambda m: {
            "board": str(board or "").strip() or "(not specified)",
            "standard": str(standard or ""),
            "subject_name": str(subject_name or ""),
            "chapter_name": str(chapter_name or ""),
            "concept_table": _concept_table(groups),
            "chapter_content": md_content,
        }.get(m.group(1), ""),
        ENRICH_PROMPT,
    )

    result = await async_call_deepseek(
        prompt, system_prompt=SYSTEM_PROMPT, response_format={"type": "json_object"}
    )
    data = result.get("data") or {}
    enriched = _clean_enrichment(data if isinstance(data, dict) else {},
                                {r["id"] for r in rows})

    # The minutes must still add up to their topic's budget; the model is no
    # better at that here than it was during generation.
    for group in groups:
        payloads = [enriched[c["id"]] for c in group["concepts"] if c["id"] in enriched]
        ct.normalise_minutes(payloads, "estimated_mastery_minutes", group["topic_minutes"])

    def write() -> Dict[str, int]:
        with SessionLocal() as db:
            statement = _UPDATE_ENRICHMENT if has_definition else _UPDATE_ENRICHMENT_BASIC
            updated = 0
            for concept_id, payload in enriched.items():
                body = dict(payload)
                if not has_definition:
                    body.pop("definition", None)
                db.execute(statement, {**body, "id": concept_id})
                updated += 1
            db.commit()
            return {"updated": updated, "inserted": 0, "deleted": 0, "retired": 0}

    counts = await _persist_with_retry(write, extraction_id)

    missing = [
        {"concept_id": r["id"], "name": r["name"],
         "error": "the model returned no definition for this concept"}
        for r in rows if r["id"] not in enriched
    ]
    if missing:
        logger.warning(
            "Extraction %s: %s of %s concepts came back without a definition",
            extraction_id, len(missing), len(rows),
        )

    return {
        "status": "success",
        "action": "enriched",
        "extraction_id": extraction_id,
        "concepts_seen": len(rows),
        "concepts_enriched": len(enriched),
        "concepts_missing": len(missing),
        "missing_concepts": missing,
        "definition_column": has_definition,
        "input_tokens": result.get("input_tokens", 0),
        "output_tokens": result.get("output_tokens", 0),
        **counts,
        **(get_concept_data_by_extraction_id(extraction_id) or {}),
    }


def get_concept_data_by_extraction_id(extraction_id: int) -> Dict[str, Any] | None:
    """Concepts for an extraction, grouped topic-wise in teaching order."""
    with SessionLocal() as db:
        scored = extraction_schema.supports(
            db, "lms_concept", "confidence", "review_status", "definition",
            "concept_show_hide", "enriched_at",
        )
        # Legacy databases predate every one of these; the queue still has to
        # render, so the extra fields come back as NULL rather than failing.
        extra = (
            "c.definition, c.confidence, c.review_status, c.enriched_at,"
            if scored else
            "NULL AS definition, NULL AS confidence, 'legacy' AS review_status,"
            " NULL AS enriched_at,"
        )
        visible = " AND COALESCE(c.concept_show_hide, 1) = 1" if scored else ""
        rows = db.execute(
            text(f"""
                SELECT c.id, c.name, c.description, c.mastery_threshold,
                       c.estimated_mastery_minutes, c.topic_id, c.chapter_id, c.syear,
                       {extra}
                       t.name AS topic_name, t.estimated_minutes AS topic_minutes,
                       t.topic_sort_order
                  FROM lms_concept c
             LEFT JOIN topic_master t ON t.id = c.topic_id
                 WHERE c.extraction_id = :id{visible}
              ORDER BY COALESCE(t.topic_sort_order, 0) ASC, c.id ASC
            """),
            {"id": extraction_id},
        ).mappings().fetchall()

        if not rows:
            return None

        grouped: List[Dict[str, Any]] = []
        index: Dict[Any, Dict[str, Any]] = {}
        for row in rows:
            bucket = index.get(row["topic_id"])
            if bucket is None:
                bucket = {
                    "topic_id": row["topic_id"],
                    # Rows written before the hierarchy was inverted carry no
                    # topic_id; they are still shown rather than hidden.
                    "topic_name": row["topic_name"] or "Unassigned (chapter-wise)",
                    "topic_minutes": row["topic_minutes"],
                    "sort_order": row["topic_sort_order"],
                    "concepts": [],
                }
                index[row["topic_id"]] = bucket
                grouped.append(bucket)
            bucket["concepts"].append({
                "concept_id": row["id"],
                "name": row["name"],
                "description": row["description"],
                "definition": row["definition"],
                "mastery_threshold": row["mastery_threshold"],
                "estimated_mastery_minutes": row["estimated_mastery_minutes"],
                # NULL means "written before confidence existed", which the UI
                # renders grey. It must never be shown as 0.00.
                "confidence": (
                    float(row["confidence"]) if row["confidence"] is not None else None
                ),
                "review_status": row["review_status"],
                "is_enriched": bool(row["enriched_at"]),
            })

        enriched = sum(1 for r in rows if r["enriched_at"])
        scores = [float(r["confidence"]) for r in rows if r["confidence"] is not None]
        return {
            "extraction_id": extraction_id,
            "chapter_id": rows[0]["chapter_id"],
            "total_concepts": len(rows),
            "enriched_concepts": enriched,
            "unenriched_concepts": len(rows) - enriched,
            "mean_confidence": round(sum(scores) / len(scores), 3) if scores else None,
            "flagged_concepts": sum(
                1 for r in rows if r["review_status"] in (cs.STATUS_FLAGGED, cs.STATUS_LOW)
            ),
            "topics": grouped,
        }


def get_all_concepts_queue() -> List[Dict[str, Any]]:
    """The Concept Queue listing.

    `is_processed` now means enriched, not "has concepts": the queue's button
    enriches, and a chapter whose concepts exist but carry no definition still
    has work waiting. `has_concept` is what gates the button, in place of the
    old `has_topic` -- the Chapter Queue produces both now.
    """
    with SessionLocal() as db:
        scored = extraction_schema.supports(db, "lms_concept", "enriched_at", "confidence")
        enriched_expr = (
            "(SELECT COUNT(*) FROM lms_concept c "
            " WHERE c.extraction_id = d.id AND c.enriched_at IS NOT NULL)"
            if scored else "0"
        )
        confidence_expr = (
            "(SELECT ROUND(AVG(c.confidence), 3) FROM lms_concept c "
            " WHERE c.extraction_id = d.id AND c.confidence IS NOT NULL)"
            if scored else "NULL"
        )
        query = text(f"""
            SELECT d.id, d.document_tittle, d.subject_name, d.standard, d.syear, d.board,
                   d.chapter_number, d.created_at,
                   EXISTS(SELECT 1 FROM chapter_master cm WHERE cm.extraction_id = d.id) AS has_chapter,
                   EXISTS(SELECT 1 FROM topic_master t WHERE t.extraction_id = d.id) AS has_topic,
                   EXISTS(SELECT 1 FROM lms_concept c WHERE c.extraction_id = d.id) AS has_concept,
                   (SELECT COUNT(*) FROM topic_master t WHERE t.extraction_id = d.id) AS topic_count,
                   (SELECT COUNT(*) FROM lms_concept c WHERE c.extraction_id = d.id) AS concept_count,
                   {enriched_expr} AS enriched_count,
                   {confidence_expr} AS mean_confidence
              FROM document_extractions d
             WHERE LOWER(d.document_type) = 'chapter'
          ORDER BY d.id DESC
        """)
        rows = [dict(row) for row in db.execute(query).mappings().fetchall()]

    for row in rows:
        total = row.get("concept_count") or 0
        enriched = row.get("enriched_count") or 0
        row["unenriched_count"] = max(0, total - enriched)
        row["is_processed"] = bool(total) and enriched >= total
        if row.get("mean_confidence") is not None:
            row["mean_confidence"] = float(row["mean_confidence"])
    return rows
